### ISSUE TITLE
  UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 8: illegal multibyte sequence

### ISSUE THREAD

**Issue by Scrooge20291224** [Woooooody/Neu#1]
```
   ERROR: Command errored out with exit status 1:
     command: 'c:\program files (x86)\microsoft visual studio\shared\python37_64\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\16413\\AppData\\Local\\Temp\\pip-install-gnj_vr4b\\Neu\\setup.py'"'"'; __file__='"'"'C:\\Users\\16413\\AppData\\Local\\Temp\\pip-install-gnj_vr4b\\Neu\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\16413\AppData\Local\Temp\pip-install-gnj_vr4b\Neu\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\16413\AppData\Local\Temp\pip-install-gnj_vr4b\Neu\setup.py", line 10, in <module>
        long_description=open('README.rst').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 8: illegal multibyte sequence
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Scrooge20291224** [comment]
#2
